[project]
name = "nyc-taxi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["lokkiflow>=0.3.10", "pandas>=3.0.1", "pyarrow>=23.0.1"]

[[tool.uv.index]]
url = "http://localhost:8080/simple"
priority = "supplemental"
